### PR TITLE
(v1.4) Better support Relay Modern

### PR DESCRIPTION
**Pull request by bruce**
(Note to future @bruce: **DO NOT SQUASH** this PR when merging)

This PR supports applying the schema definition macros to target Relay Classic or Modern, based on an option, eg:

```elixir
use Absinthe.Relay.Schema, :modern
```

It will serve as the base for the v1.4 release, but will be backwards compatible with v1.3. If `:classic` or `:modern` are not specified, `:classic` will be selected and a deprecation notice will indicate that in v1.5 the default will switch to `:modern`.

### CODE REVIEW

**Comment by bruce** [comment]
- [ ] Fix for #78

**Comment by bruce** [comment]
- [ ] Reminder for @bruce: DO NOT SQUASH this PR when merging, as doing so will throw away GH contribution credit for PRs that used `next` as the base.

**Comment by bruce** [comment]
- [ ] Absinthe.Relay.Mutation: Make `input` optional (see @tlvenn's https://github.com/jumpn/absinthe_relay/commit/a7f8da0f9146b6f37fe1338600f2e1bfc3eb694b for reference)

**Comment by avitex** [comment]
This is fantastic! I haven't looked at the spec for modern yet, but I can see this will resolve #55 as a side effect

**Comment by bruce** [comment]
- [x] Update absinthe dep to target any of 1.4.0 beta/rc/stable
- [x] Remove ExSpec, update dev deps

**Comment by bruce** [comment]
I chatted a bit with @tlvenn a bit about Relay Modern, especially with regard to mutations. In general, I think Relay Modern has reached the point now where the `payload` macro isn't _necessary_, but a nicety that our users have become accustomed to that helps with the common boilerplate of creating input and output object types (and automatically handling the clientMutationId, if in compatibility mode).

Here is my draft plan:

I'm going to fully split `Absinthe.Relay.Mutation.Notation.Modern` and `Absinthe.Relay.Mutation.Notation.Classic`. At this point having them both `use Absinthe.Relay.Mutation.Notation` with some `defoverridable` fields works, but as they diverge (and, see below, I think they are doing that) it's going to be harder and harder to understand what's going on.

So if you `use Absinthe.Relay.Schema, :modern`, you'll get a completely different implementation of the macros for mutations. Here's how I think they'll work:


With an `input` block, you'll get a `:input` arg and a `*_input

**Comment by bruce** [comment]
In a given `payload field :foo do ... end` block:

## Input

If you provide an `input` block with one-or-more fields, you'll get an `:input` arg generated with a matching `:foo_input` input object type with those fields. A special macro, `client_mutation_id_field` will be available; if used inside the `input` block, it will add a `:client_mutation_id` field (whose value will be transparently returned if an `output` type is also defined; see below).

An `input` block without any fields declared will result in a compile error (prevent empty object type).

### Examples:

#### Fully Defined

```elixir
input do
  client_mutation_id_field
  field :name, :string
end
```

Yields:

```elixir
object :foo_input do
  field :client_mutation_id, :id
  field :name, :string
end

# In the definition of the `:foo` field:
arg :input, :foo_input
```

#### Without a clientMutationId

```elixir
input do
  field :name, :string
end
``

Yields:

```elixir
object :foo_input do
  field :name, :string
end

# In the definition of the `:foo` field:
arg :input, :foo_input
```

#### Empty

```elixir
input do
end
``

(Yields error during compilation.)

(cont.)

**Comment by bruce** [comment]
In a given `payload field :foo do ... end` block:

## Output

If you provide an `output` block with one-or-more fields, you'll get a `:foo_payload` object type with those fields. If the special macro, `client_mutation_id_field` was defined as part of the `input` block, it will be added to the payload type and transparently returned.

An `output` block without any fields declared will result in a compile error.

### Examples:

#### With a field

```elixir
output do
  field :name, :string
end
``
Is equivalent to:

```elixir
object :foo_payload do
  field :name, :string
  # If there's an `input` block that uses `client_mutation_id_field`:
  field :client_mutation_id, :id
end

# (and set the return type of the :foo field to :foo_payload)
```

#### Missing

If `client_mutation_id_field` was used in an `input` block, we'll define a payload type with just it for you:

```elixir
object :foo_payload do
  field :client_mutation_id, :id
end

# (and set the return type of the :foo field to :foo_payload)
```

If `client_mutation_id_field` *was not defined* in an `input` block, an error will occur during compilation. If you don't need a payload object, you probably shouldn't be using a macro with the word "payload" in it. Just use a normal mutation field!

#### Empty

```elixir
output do
end
``

(Yields error during compilation.)

**Comment by bruce** [comment]
I'm looking for feedback on the above.

Note: This issue will likely be paused until after ElixirConf (end of next week).

**Comment by bruce** [comment]
BTW, worth mentioning here: I think it's important we don't "just make everything optional." The Relay Classic support should remain strict.

Also: A completely reasonable feedback to the above is "Relay Modern isn't strict enough to warrant a complex macro system, just define what you need using normal macros." If that's how you feel, please let me know––this is the most complex set of macros in any (official, at least) Absinthe project already. Is it worth it, providing what I outlined above? Opinions wanted!

**Comment by dpehrson** [comment]
Based on my week-long experience with relay modern so far, this seems reasonable.

I would be curious if the `input` and `output` macros could still automatically include the `clientMutationId` field when the `Schema` is configured with `:classic` rather than having to explicitly define it with `client_mutation_id_field`?

**Comment by bruce** [comment]
@dpehrson I think if you use `:classic`, the same old rules apply.

**Comment by bruce** [comment]
I'm going to be going through this in the next few days and seeing whether it makes sense to pull these changes in now.

After thinking about things a bit since posting my suggestions above, I think it's prudent to wait on the more complex macros until _after_ we work on the major changes we plan to make in Absinthe v1.5 to support more flexible schema definitions. To be honest, the macros in here are complex enough that they've managed to prevent almost anyone but the author (me!) from contributing fixes and enhancements up to this point. I don't want to make things _more_ opaque to everyone else.

So, we want something narrower and more focused for this v1.4 release. I just need to think a bit about what it should be.

**Pull request merged**
