### PR TITLE
Allow non null connections

### PR DESCRIPTION
**Pull request by beagleknight**
This closes https://github.com/absinthe-graphql/absinthe_relay/issues/107 allowing `non_null` connections. I followed the same approach as edges and nodes. This is very useful when you are generating types from a fronted application using https://www.graphql-code-generator.com/

Apologies for not including tests. At the moment I don't have time to do it, but I'll try during the next days.

Kudos to @mrcasals for helping me with this! 😄

### CODE REVIEW

**Comment by mrcasals** [comment]
Hi @benwilson512! Could you check this out, please? 😄

**Comment by mrcasals** [comment]
Hi @tlvenn @mgtitimoli! Could you check this out, please? 😄 GitHub says you're a member of the `absinthe-graphql` group!

**Comment by benwilson512** [comment]
@beagleknight @mrcasals this PR needs tests before it can be accepted.

**Comment by mrcasals** [comment]
@benwilson512 I've added tests! Those tests don't even run on current `master`, they raise this error:

```
$ mix test ./test/lib/absinthe/relay/connection_test.exs
Compiling 2 files (.ex)
Excluding tags: [pending: true]


== Compilation error in file test/lib/absinthe/relay/connection_test.exs ==
** (KeyError) key :non_null_connection not found in: %Absinthe.Blueprint.Schema.ObjectTypeDefinition{__private__: [], __reference__: %{location: %{file: "/Users/marc/code/elixir/absinthe_relay/test/lib/absinthe/relay/connection_test.exs", line: 163}, module: Absinthe.Relay.ConnectionTest.CustomConnectionAndEdgeFieldsSchema}, description: nil, directives: [], errors: [], fields: [], flags: %{}, identifier: :non_null_connection_connection, imports: [], interface_blueprints: [], interfaces: [], is_type_of: nil, module: Absinthe.Relay.ConnectionTest.CustomConnectionAndEdgeFieldsSchema, name: "NonNullConnectionConnection", source_location: nil}
    (stdlib 3.15) :maps.update(:non_null_connection, true, %Absinthe.Blueprint.Schema.ObjectTypeDefinition{__private__: [], __reference__: %{location: %{file: "/Users/marc/code/elixir/absinthe_relay/test/lib/absinthe/relay/connection_test.exs", line: 163}, module: Absinthe.Relay.ConnectionTest.CustomConnectionAndEdgeFieldsSchema}, description: nil, directives: [], errors: [], fields: [], flags: %{}, identifier: :non_null_connection_connection, imports: [], interface_blueprints: [], interfaces: [], is_type_of: nil, module: Absinthe.Relay.ConnectionTest.CustomConnectionAndEdgeFieldsSchema, name: "NonNullConnectionConnection", source_location: nil})
    (absinthe 1.6.0) lib/absinthe/blueprint/schema/object_type_definition.ex:7: anonymous fn/2 in Absinthe.Blueprint.Schema.ObjectTypeDefinition.__struct__/1
    (elixir 1.12.2) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (absinthe 1.6.0) lib/absinthe/blueprint/schema/object_type_definition.ex:7: Absinthe.Blueprint.Schema.ObjectTypeDefinition.__struct__/1
    (elixir 1.12.2) lib/kernel.ex:2285: Kernel.struct!/2
    (absinthe 1.6.0) lib/absinthe/schema/notation.ex:1597: Absinthe.Schema.Notation.scoped_def/5
    (absinthe 1.6.0) expanding macro: Absinthe.Schema.Notation.object/3
    test/lib/absinthe/relay/connection_test.exs:163: Absinthe.Relay.ConnectionTest.CustomConnectionAndEdgeFieldsSchema (module)
    (absinthe_relay 1.5.1) expanding macro: Absinthe.Relay.Connection.Notation.connection/2
    test/lib/absinthe/relay/connection_test.exs:163: Absinthe.Relay.ConnectionTest.CustomConnectionAndEdgeFieldsSchema (module)
    (elixir 1.12.2) lib/kernel/parallel_compiler.ex:428: Kernel.ParallelCompiler.require_file/2
    (elixir 1.12.2) lib/kernel/parallel_compiler.ex:321: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

I hope tests are clear enough! 😄

**Comment by mrcasals** [comment]
@benwilson512 apparently you need to manually approve the workflow before it runs 😄

**Comment by mrcasals** [comment]
@benwilson512 could you review this, please? 😄

**Comment by pantiushenkov** [comment]
@benwilson512, asking to review as well please 🙏

**Comment by michaelst** [comment]
It would be great if this could be merged to clean up generated types

**Comment by scrogson** [comment]
@benwilson512 any chance we can get this in soon? We've just recently bumped into this and my frontend folks are complaining about it 😄

**Comment by zsaraf** [comment]
@benwilson512 I'm having issues with this as well, would really love a fix.

**Comment by benwilson512** [comment]
This looks great, I'll try to get a release our shortly, thanks!

**Comment by scrogson** [comment]
@benwilson512 thanks boss!

**Comment by michaelst** [comment]
Any idea of when you can create a release?

**Pull request merged**
