### PR TITLE
Change non_null_node_type to non_null_style

### PR DESCRIPTION
**Pull request by jeroenvisser101**
This is an alternative way of introducing `non_null` types to connection/connection fields.

I'm very much aware that this isn't an intuitive behaviour (as setting `node_type: non_null(type)` should generally not change the type of Edge or Edges), but I believe that if anyone is marking the node_type as `non_null`, the reasoning for that is because it will always be available if it's in the list, and that therefor, the Edge and Edges should also be available (where Edges can still be an empty list, it can just not be null or contain null values).

WDYT?

### CODE REVIEW

**Comment by jeroenvisser101** [comment]
(this doesn't yet update the tests but if this would be an accepted solution than I'd be open to rewriting them too)

**Comment by benwilson512** [comment]
Maybe I'm missing something but isn't this what the `non_null_node_type: true/false` option already does?

**Comment by jeroenvisser101** [comment]
The non_null_node_type does something *very* similar, but only applies to the type for `edges { edge { node } }`, where 'edges' and 'edge' are possibly null. Now, this change would apply the non_null not only to node but to all three fields, fixing #107.

**Comment by hadfieldn** [comment]
Any chance of getting this merged in? I'd be happy to help with tests as well, if this solution is accepted. I agree that it's preferreed to #134 because it supports making the `edges` and `edge` non-null as well as the `node`. This is important for automatic generation of TypeScript types from GraphQL because it reduces the need to check for nulls.

**Comment by rjdellecese** [comment]
This looks great! We use a library that auto-generates Elm code for our GraphQL (https://github.com/dillonkearns/elm-graphql), and this would also help us with not needing to account for impossible nulls there. Would also be happy to help with the tests if this solution is accepted!

**Comment by jeroenvisser101** [comment]
@rjdellecese we use something similar for Apollo/TypeScript: https://graphql-code-generator.com/

I think this would go a long way indeed to improve developer experience on the *client side* for those working with Absinthe GraphQL APIs.

**Comment by hadfieldn** [comment]
Just bumping this issue.. any chance of getting a resolution on this soon?

**Comment by jeroenvisser101** [comment]
Update from my side: this PR is outdated as the way that non-nulls are handled in 1.5 is a bit different now. 

Node types seem like a possibility now, but it seems to partially support what we need, and the Naming module doesn't handle everything (https://github.com/absinthe-graphql/absinthe_relay/blob/master/lib/absinthe/relay/connection/notation.ex#L17-L51).

If this is considered by @benwilson512 or @bruce as something that would be accepted, I can take a stab at this again?

**Comment by jeroenvisser101** [comment]
I preliminarily added this functionality, it seems to work just fine:

https://github.com/novistore/absinthe_relay/tree/v1.5-non-null-edge-types

usage (with or without inline do, whichever style you prefer):
```elixir
  connection node_type: :product, non_null: true do
    edge(do: field(:node, non_null(:product)))
  end
```

`non_null` is a shorthand to set the edges and edge itself to non-null, `Connection.edges: [Edge!]!` would be the gql representation. The node would be non-null in your connection type definition.

Tests are still pending

**Comment by jeroenvisser101** [comment]
We've been using the above in production and it's been working nicely. I hope to wrap this up in a PR soon, but if anyone wants to take a stab at this before then, go ahead :)

**Comment by jeroenvisser101** [comment]
Closing in favor of #158

**Pull request closed without merging**
