### PR TITLE
Enhancements to Connection builder functions to allow inclusion of edge data

### PR DESCRIPTION
**Pull request by coderdan**
In the [spec](https://facebook.github.io/relay/graphql/connections.htm#sec-Edge-Types.Fields) for connections described by Facebook, edges can be defined with arbitrary fields.

This pull request provides additional capabilities to the `Absinthe.Relay.Connection` module, specifically via changes to the private `build_cursors` functions to allow resolving of edge data.

For example:

```graphql
{
  team(id: 1) {
    users(first: 5) {
      edges {
        role
        node {
          email
        }
      }
    }
  }
}
```

While Absinthe Relay does support defining fields on edges, these fields can only be resolved based on data already provided on the node. In many cases it may be useful to have edge data resolved from a database query or other service.

### CODE REVIEW

**Comment by bruce** [comment]
Thanks for the PR (and especially adding clear documentation and tests). I like the general direction of this; let me play around with it a bit tomorrow in a larger project and see how it feels, how it might interact with dataloader, etc.

**Comment by bruce** [comment]
@coderdan First off, thanks for digging into this. Making edges easier to work with is a great goal (and one that's been sorely needed).

My only real issue with this approach, after playing with it a bit, is the magic assignment to `predicate`. I'm wary of adding yet another term to an already crowded set of nomenclature, and especially when it's not already in Relay's Cursor Connection Specification. ("Predicate," too, runs afoul of some people's mental baggage with "predicate methods.")

I also think that the tuple approach would perhaps be a bit more intuitive if the node was in the 0th element place. What do you think about a form that was a bit more explicit and looked something like this?:

```elixir
{node, predicate: your_edge_predicate_field, other_explicit_field: your_other_edge_field}
```

**Comment by coderdan** [comment]
Thanks for the feedback @bruce! I quite like your suggestion actually. I'll will have a play with it this week and push an update. Cheers!

**Comment by coderdan** [comment]
@bruce any thoughts on this one?

**Comment by bruce** [comment]
Sorry about the delay in reviewing!

Good work here. 🙂

I think those keys should be ignored (and a warning logged if present, to prevent debugging frustration).

**Comment by coderdan** [comment]
My turn to apologise for the slow response @bruce. Made the changes you suggested so should be ready to go. Let me know of any issues.

**Comment by bruce** [comment]
@coderdan I made some small changes, just to docs and tests. Could you look those over?

Also, I noticed you're still allowing override of the internally generated `:cursor` value. Is this intentional? I can't personally think of a case I'd want to build by own cursor logic this way, but that's not to say others won't. I'm okay keeping the override if you think there's a compelling use case there.

**Comment by coderdan** [comment]
Hi @bruce any update on this one?

**Comment by coderdan** [comment]
Bump :)

**Pull request merged**
