### PR TITLE
remove ecto and poison from list of dependencies

### PR DESCRIPTION
**Pull request by lizziepaquette**

### CODE REVIEW

**Comment by benwilson512** [comment]
Hi @lizziepaquette, thanks for the interest in the project. However, Ecto is definitely not unused, it's an optional dependency to support the paginators. https://github.com/absinthe-graphql/absinthe_relay/blob/4676c46ef11ad951d1c65909d931350d91c36878/lib/absinthe/relay/connection.ex#L441

**Comment by TMSCH** [comment]
I'm not sure to understand @benwilson512 - as far as I can tell this part of the code is optional and should only be available if `Ecto` is available and loaded in the application that uses `absinthe_relay`. Adding `Ecto` as a dependency here makes it *always* present.

Am I missing something?

**Comment by TMSCH** [comment]
[`"You cannot use this unless Ecto is also a dependency"`](https://github.com/absinthe-graphql/absinthe_relay/blob/4676c46ef11ad951d1c65909d931350d91c36878/lib/absinthe/relay/connection.ex#L473) definitely sounds like the expectation and usage is to add `:ecto` as a deps of the app using `absinthe_relay` :)

**Comment by benwilson512** [comment]
That is the expectation if you want to use the `from_query` function. I think you're confused about how optional dependencies work. If `absinthe_relay` did not specify `ecto` as an optional dependency then `mix` wouldn't know to make sure to compile `ecto` prior to compiling `absinthe_relay`. If `ecto` were to be compiled after `absinthe_relay` then the `if Code.ensure_loaded?` calls would return false and the project would compile as if `ecto` were not included.

Including ecto as an optional dependency is the only want to enable both: use of  `absinthe_relay` without ecto and also use of `absinthe_relay` with ecto specific functions.

**Comment by TMSCH** [comment]
Oh ok my bad. Thanks for the explanation :)

**Comment by benwilson512** [comment]
No problem! I still appreciate the PR, it's always great to see people take a crack at solving a problem :)

**Pull request closed without merging**
