### PR TITLE
Much better pagination

### PR DESCRIPTION
**Pull request by benwilson512**
@bruce this does not yet support backwards pagination properly. Most of the logic is here but it needs tests as well as `has_previous_page` logic.

### CODE REVIEW

**Comment by bruce** [comment]
@benwilson512 I merged in #13; if you need help resolving any merge conflicts let me know. I'd like to release this + the work from that PR together in v0.9.0.

**Comment by benwilson512** [comment]
@bruce if you get a chance to look at this that would be ideal.

**Comment by bruce** [comment]
Will look at this in the morning.

**Comment by bruce** [comment]
We talked about a couple doc changes, but :shipit: !

**Pull request merged**
